version: '3.8'

services:
  mintutil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mintutil
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tools:/app/tools
      - ./scripts:/app/scripts
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app/main.py
    restart: unless-stopped

  # Placeholder for additional services
  # redis:
  #   image: redis:alpine
  #   container_name: mintutil-redis
  #   ports:
  #     - "6379:6379"

volumes:
  mintutil-data:
  mintutil-logs:

networks:
  default:
    name: mintutil-network
