# MINTutil Docker Compose Configuration
# Copyright (c) 2025 MINT-RESEARCH
# Contact: mint-research@neomint.com

version: '3.8'

services:
  mintutil:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: mintutil:latest
    container_name: mintutil
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Berlin
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./tools:/app/tools:ro
      - ./scripts:/app/scripts:ro
      - ./config:/app/config:rw
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    restart: unless-stopped
    networks:
      - mintutil-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  # Redis cache service (optional)
  redis:
    image: redis:7-alpine
    container_name: mintutil-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mintutil-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  mintutil-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
