name: NeoMINT Compliance Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  compliance-check:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup PowerShell
      shell: pwsh
      run: |
        Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
    
    - name: Run NeoMINT Compliance Check
      shell: pwsh
      run: |
        Write-Host "Starting NeoMINT Compliance Check..." -ForegroundColor Cyan
        .\scripts\check-neomint-compliance.ps1 -Verbose
    
    - name: Upload compliance report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: compliance-report
        path: logs/
        retention-days: 30
